# Generated by Django 4.2.20 on 2025-04-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_problems", models.IntegerField()),
                ("answer", models.IntegerField(default=0)),
                ("type_of_problem", models.CharField(default="m", max_length=2)),
                ("user_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Mechanics",
            fields=[
                ("number", models.AutoField(primary_key=True, serialize=False)),
                ("condition", models.TextField()),
                ("answer", models.CharField(max_length=300)),
                ("comment", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_problems", models.IntegerField()),
                ("condition", models.TextField()),
                ("answer", models.CharField(max_length=300)),
                ("user_answer", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Thermodynamics",
            fields=[
                ("number", models.AutoField(primary_key=True, serialize=False)),
                ("condition", models.TextField()),
                ("answer", models.CharField(max_length=300)),
                ("comment", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=20)),
                ("flag", models.IntegerField(default=0)),
            ],
        ),
    ]
